
all: marzone_test

marzone_test:  
	g++ -O3 -std=c++17 \
	main_test.cpp utils_test.cpp costs_test.cpp species_test.cpp pu_test.cpp zones_test.cpp reserve_test.cpp \
	-o test -lCppUTest -lCppUTestExt 
